// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DBProxyClient is the client API for DBProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DBProxyClient interface {
	Dau(ctx context.Context, in *GameReq, opts ...grpc.CallOption) (*DauRsp, error)
	TxCount(ctx context.Context, in *GameReq, opts ...grpc.CallOption) (*TxCountRsp, error)
	ChainDau(ctx context.Context, in *ChainGameReq, opts ...grpc.CallOption) (*DauRsp, error)
	ChainTxCount(ctx context.Context, in *ChainGameReq, opts ...grpc.CallOption) (*TxCountRsp, error)
}

type dBProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewDBProxyClient(cc grpc.ClientConnInterface) DBProxyClient {
	return &dBProxyClient{cc}
}

func (c *dBProxyClient) Dau(ctx context.Context, in *GameReq, opts ...grpc.CallOption) (*DauRsp, error) {
	out := new(DauRsp)
	err := c.cc.Invoke(ctx, "/DBProxy/Dau", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProxyClient) TxCount(ctx context.Context, in *GameReq, opts ...grpc.CallOption) (*TxCountRsp, error) {
	out := new(TxCountRsp)
	err := c.cc.Invoke(ctx, "/DBProxy/TxCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProxyClient) ChainDau(ctx context.Context, in *ChainGameReq, opts ...grpc.CallOption) (*DauRsp, error) {
	out := new(DauRsp)
	err := c.cc.Invoke(ctx, "/DBProxy/ChainDau", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProxyClient) ChainTxCount(ctx context.Context, in *ChainGameReq, opts ...grpc.CallOption) (*TxCountRsp, error) {
	out := new(TxCountRsp)
	err := c.cc.Invoke(ctx, "/DBProxy/ChainTxCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBProxyServer is the server API for DBProxy service.
// All implementations must embed UnimplementedDBProxyServer
// for forward compatibility
type DBProxyServer interface {
	Dau(context.Context, *GameReq) (*DauRsp, error)
	TxCount(context.Context, *GameReq) (*TxCountRsp, error)
	ChainDau(context.Context, *ChainGameReq) (*DauRsp, error)
	ChainTxCount(context.Context, *ChainGameReq) (*TxCountRsp, error)
	mustEmbedUnimplementedDBProxyServer()
}

// UnimplementedDBProxyServer must be embedded to have forward compatible implementations.
type UnimplementedDBProxyServer struct {
}

func (UnimplementedDBProxyServer) Dau(context.Context, *GameReq) (*DauRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dau not implemented")
}
func (UnimplementedDBProxyServer) TxCount(context.Context, *GameReq) (*TxCountRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxCount not implemented")
}
func (UnimplementedDBProxyServer) ChainDau(context.Context, *ChainGameReq) (*DauRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainDau not implemented")
}
func (UnimplementedDBProxyServer) ChainTxCount(context.Context, *ChainGameReq) (*TxCountRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChainTxCount not implemented")
}
func (UnimplementedDBProxyServer) mustEmbedUnimplementedDBProxyServer() {}

// UnsafeDBProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBProxyServer will
// result in compilation errors.
type UnsafeDBProxyServer interface {
	mustEmbedUnimplementedDBProxyServer()
}

func RegisterDBProxyServer(s grpc.ServiceRegistrar, srv DBProxyServer) {
	s.RegisterService(&DBProxy_ServiceDesc, srv)
}

func _DBProxy_Dau_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProxyServer).Dau(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DBProxy/Dau",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProxyServer).Dau(ctx, req.(*GameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProxy_TxCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProxyServer).TxCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DBProxy/TxCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProxyServer).TxCount(ctx, req.(*GameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProxy_ChainDau_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainGameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProxyServer).ChainDau(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DBProxy/ChainDau",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProxyServer).ChainDau(ctx, req.(*ChainGameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProxy_ChainTxCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainGameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProxyServer).ChainTxCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DBProxy/ChainTxCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProxyServer).ChainTxCount(ctx, req.(*ChainGameReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DBProxy_ServiceDesc is the grpc.ServiceDesc for DBProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DBProxy",
	HandlerType: (*DBProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dau",
			Handler:    _DBProxy_Dau_Handler,
		},
		{
			MethodName: "TxCount",
			Handler:    _DBProxy_TxCount_Handler,
		},
		{
			MethodName: "ChainDau",
			Handler:    _DBProxy_ChainDau_Handler,
		},
		{
			MethodName: "ChainTxCount",
			Handler:    _DBProxy_ChainTxCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
