LogFile = "avax_gamefidata.log"
LogPath = "./"
LogLevel = "Info"
PrivKey = ""
#DBURI = "mongodb+srv://cz:Solong2020@cluster1.g9w77.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
DBURI = "mongodb+srv://gametaverse:gametaverse2021@cluster0.fnwxw.mongodb.net/d_gametaverse?retryWrites=true&w=majority"
Chain = "avax"
ChainID = 43114
RPCAddr = "https://api.avax.network/ext/bc/C/rpc"
BottomBlock = 100000
ForwardInterval = 1.0
BackwardInterval = 1.0
ForwardWorks = 1
BackwardWorks = 1

[[Games]]
    Name = "Trader Joe"
    ID  = "trader_joe"
    [[Games.Contracts]]
        Address="0xd6a4F121CA35509aF06A0Be99093d08462f53052"
        Type = ""
    [[Games.Contracts]]
        Address="0x9Ad6C38BE94206cA50bb0d90783181662f0Cfa10"
        Type = ""
    [[Games.Contracts]]
        Address="0x60aE616a2155Ee3d9A68541Ba4544862310933d4"
        Type = ""
    [[Games.Contracts]]
        Address="0x188bED1968b795d5c9022F6a0bb5931Ac4c18F00"
        Type = ""
  