LogFile = "polygon_gamefidata.log"
LogPath = "./"
LogLevel = "Info"
PrivKey = ""
DBURI = "mongodb+srv://cz:Solong2020@cluster1.g9w77.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
Chain = "polygon"
ChainID = 137
RPCAddr = "https://rpc-mainnet.maticvigil.com"
BottomBlock = 12953057
Interval = 2

[[Games]]
    Name = "Zed Run"
    ID  = "zed_run"
    [[Games.Contracts]]
        Address = "0xA5F1Ea7DF861952863dF2e8d1312f7305dabf215"
        Type = "erc721"
    [[Games.Contracts]]
        Address = "0x6f9F251551f92cec48C43ba59598fd7b07387F95"
        Type = "game"
    [[Games.Contracts]]
        Address = "0x8221735b9d7c2a1E9B2D76B214ab39466750872e"
        Type = "game"
    [[Games.Contracts]]
        Address = "0xb6602D1f76A2d6a73FE839Cb3Fc4b7e0D9eC5544"
        Type = "game"
    [[Games.Contracts]]
        Address = "0xb6602D1f76A2d6a73FE839Cb3Fc4b7e0D9eC5544"
        Type = "game"

