LogFile = "gamefidata.log"
LogPath = "./"
LogLevel = "Info"
PrivKey = ""
DBURI = "mongodb+srv://gametaverse:gametaverse2021@cluster0.fnwxw.mongodb.net/d_gametaverse?retryWrites=true&w=majority"

[ETHConfig]
    [[ETHConfig.Games]]
        Name = "zed.run"
        URL = "https://zed.run"
        Chain = "polygon"
        ChainID = 137
        RPCAddr = "https://rpc-mainnet.maticvigil.com"
        [[ETHConfig.Games.Contracts]]
            Address = "0xA5F1Ea7DF861952863dF2e8d1312f7305dabf215"
            StartBlock = "19102371"
            Type = "erc721"
