LogFile = "solana_gamefidata.log"
LogPath = "./"
LogLevel = "Info"
Chain = "solana"
ChainID = 1
#RPCAddr = "https://solana-api.projectserum.com"
#RPCAddr = "https://api.wax.alohaeos.com"
#RPCAddr = "https://api.waxsweden.org"
#RPCAddr = "https://wax.pink.gg"
#RPCAddr = "https://wax.dapplica.io"
RPCAddr = "https://rpc.ankr.com/solana/89a1577615a713dddcd59aed5762cb3851fe3d050eb6c7e2a26fe39c38cb97d9"
BottomBlock = 55000000
ForwardInterval = 0.5
BackwardInterval = 0.5
ForwardWorks = 2
BackwardWorks = 10