LogFile = "wax_gamefidata.log"
LogPath = "./"
LogLevel = "Info"
Chain = "wax"
ChainID = 1
RPCAddr = "https://api.wax.alohaeos.com"
#RPCAddr = "https://api.waxsweden.org"
#RPCAddr = "https://wax.pink.gg"
#RPCAddr = "https://wax.dapplica.io"
BottomBlock = 90000000
ForwardInterval = 0.0
BackwardInterval = 0.0
ForwardWorks = 4
BackwardWorks = 10