LogFile = "eth_gamefidata.log"
LogPath = "./"
LogLevel = "Info"
PrivKey = ""
DBURI = "mongodb+srv://cz:Solong2020@cluster1.g9w77.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
#DBURI = "mongodb+srv://gametaverse:gametaverse2021@cluster0.fnwxw.mongodb.net/d_gametaverse?retryWrites=true&w=majority"
Chain = "eth"
ChainID = 1
#RPCAddr = "https://mainnet.infura.io/v3/1f48b32a51144c9fbf5b9aa4cf3a4066"
RPCAddr = "https://rpc.ankr.com/eth"
BottomBlock = 9193266
ForwardInterval = 12.0
BackwardInterval = 1.0
ForwardWorks = 1
BackwardWorks = 1

[[Games]]
    Name = "Axie Infinity"
    ID  = "axie_infinity"
    [[Games.Contracts]]
        Address="0xb28a3dd24036151c819c6d401f7a222d9aa3671b"
        Type = ""
    [[Games.Contracts]]
        Address="0x3d5be9a472d6b5c8d45b4b3a3bffb80e0c52ef15"
        Type = ""
    [[Games.Contracts]]
        Address="0xf78dbc37a67018db6f823ec5090d7eedd5bab6fd"
        Type = ""
    [[Games.Contracts]]
        Address="0xf5b0a3efb8e8e4c201e2a935f110eaaf3ffecb8d"
        Type = ""
    [[Games.Contracts]]
        Address="0x020f9e661e512132890d259dc363ed084cf4e5a6"
        Type = ""
    [[Games.Contracts]]
        Address="0xae8e74a21c25c22112749f7a9cd600d4b5cb2191"
        Type = ""
    [[Games.Contracts]]
        Address="0x8138df138b415a6f85f09a0995fec0ce3b454b5d"
        Type = ""
    [[Games.Contracts]]
        Address="0x60dbf8e1cac4e8d318a2c655d3136f9343ee386a"
        Type = ""
    [[Games.Contracts]]
        Address="0x73d7b530d181ef957525c6fbe2ab8f28bf4f81cf"
        Type = ""
    [[Games.Contracts]]
        Address="0x10e304a53351b272dc415ad049ad06565ebdfe34"
        Type = ""
    [[Games.Contracts]]
        Address="0x717ea56208b459ebeedb95c2cceee00b539c1205"
        Type = ""
    [[Games.Contracts]]
        Address="0x9b1d9c45d9da03997d7850b4c90285c538d77233"
        Type = ""
    [[Games.Contracts]]
        Address="0xd6115822be14782310b00557c52d28257a952be3"
        Type = ""
    [[Games.Contracts]]
        Address="0x60ce035dc589c3fd185b224a7ca03c598948973b"
        Type = ""
    [[Games.Contracts]]
        Address="0x436fb447a25d90965b6311e931682f7279d03226"
        Type = ""
    [[Games.Contracts]]
        Address="0x0c7cf86188632e16af00415214155950684466a8"
        Type = ""
    [[Games.Contracts]]
        Address="0xeba02cfc36c01acbe10f6bcb909b76749e54956a"
        Type = ""
    [[Games.Contracts]]
        Address="0x99ff9f4257d5b6af1400c994174ebb56336bb79f"
        Type = ""
    [[Games.Contracts]]
        Address="0xf429b7270f7078d5561789c15d301692e32b1e48"
        Type = ""
    [[Games.Contracts]]
        Address="0xd7af30e9066fd3b267fe8b1c3e88192006d43486"
        Type = ""
    [[Games.Contracts]]
        Address="0x71ffc95ca3bcebf26024f689f40006182916167f"
        Type = ""
    [[Games.Contracts]]
        Address="0x425372c0ac9d559a186a08a3854e0ddea1a00d5c"
        Type = ""
    [[Games.Contracts]]
        Address="0x92bf969865c80eda082fd5d8b4e28da4d58e1c3a"
        Type = ""
    [[Games.Contracts]]
        Address="0x7a11462a2adaed5571b91e34a127e4cbf51b152c"
        Type = ""
    [[Games.Contracts]]
        Address="0x2299a91cc0bffd8c7f71349da8ab03527b79724f"
        Type = ""
    [[Games.Contracts]]
        Address="0x66536a95cc83ee672da58b6d3e57f7582184d5df"
        Type = ""
    [[Games.Contracts]]
        Address="0x01aac5236ad205ebbe4f6819bc64ef5bef40b71c"
        Type = ""
    [[Games.Contracts]]
        Address="0x37236cd05b34cc79d3715af2383e96dd7443dcf1"
        Type = ""
    [[Games.Contracts]]
        Address="0x32950db2a7164ae833121501c797d79e7b79d74c"
        Type = ""
    [[Games.Contracts]]
        Address="0x8c811e3c958e190f5ec15fb376533a3398620500"
        Type = ""
    [[Games.Contracts]]
        Address="0x213073989821f738a7ba3520c3d31a1f9ad31bbd"
        Type = ""
    [[Games.Contracts]]
        Address="0xa96660f0e4a3e9bc7388925d245a6d4d79e21259"
        Type = ""
    [[Games.Contracts]]
        Address="0xa99cacd1427f493a95b585a5c7989a08c86a616b"
        Type = ""
    [[Games.Contracts]]
        Address="0xe35d62ebe18413d96ca2a2f7cf215bb21a406b4b"
        Type = ""
    [[Games.Contracts]]
        Address="0xbb0e17ef65f82ab018d8edd776e8dd940327b28b"
        Type = ""
    [[Games.Contracts]]
        Address="0xCC8Fa225D80b9c7D42F96e9570156c65D6cAAa25"
        Type = ""
    [[Games.Contracts]]
        Address="0x97a9107c1793bc407d6f527b77e7fff4d812bece"
        Type = ""
    [[Games.Contracts]]
        Address="0xa8754b9fa15fc18bb59458815510e40a12cd2014"
        Type = ""
    [[Games.Contracts]]
        Address="0xc99a6a985ed2cac1ef41640596c5a5f9f4e19ef5"
        Type = ""

[[Games]]
    Name = "Illuvium"
    ID  = "illuvium"
    [[Games.Contracts]]
        Address = "0x4222b2a98dAa443C6a0a761300d7d6bfD9161E52"
        Type = ""
    [[Games.Contracts]]
        Address = "0x9898d72c2901D09E72A426d1c24b6ab90eB100e7"
        Type = ""
    [[Games.Contracts]]
        Address = "0x8B4d8443a0229349A9892D4F7CbE89eF5f843F72"
        Type = ""
    [[Games.Contracts]]
        Address = "0x25121EDDf746c884ddE4619b573A7B10714E2a36"
        Type = ""

[[Games]]
    Name = "Sandbox"
    ID  = "sandbox"
    [[Games.Contracts]]
        Address="0x50f5474724e0ee42d9a4e711ccfb275809fd6d4a"
        Type = ""
    [[Games.Contracts]]
        Address="0xb2fb1D91325d0211B1Eb39e4CF2C9F3Cf14508b0"
        Type = ""
    [[Games.Contracts]]
        Address="0x6ce6267Fc45ABc6051aCee92BF2CC63DcC860A95"
        Type = ""
    [[Games.Contracts]]
        Address="0x126a3437F3b76155E5e574abDc048b54f2F4aDAa"
        Type = ""
    [[Games.Contracts]]
        Address="0x3a6d6Ea6014DA52561bbE889a683bD86D1413ba3"
        Type = ""
    [[Games.Contracts]]
        Address="0x36C8dd8328bFd5C6E8544f11b652C2dD5f5c95fd"
        Type = ""
    [[Games.Contracts]]
        Address="0x1b67D81902608b9765B1b068B52eA46380c4DDFc"
        Type = ""
    [[Games.Contracts]]
        Address="0xE0C07D040da3ce59C445026A9Fc677BD12ab1be1"
        Type = ""
    [[Games.Contracts]]
        Address="0x717e67692908f4002915eb5e40e0503d333059f3"
        Type = ""
    [[Games.Contracts]]
        Address="0x1cc7657c4d8d300544acc7f519cec11fd484dbee"
        Type = ""
    [[Games.Contracts]]
        Address="0x772C34049d8417Eef82B546D0e42a45f356Bdd2A"
        Type = ""
    [[Games.Contracts]]
        Address="0x3EEe9C3De463a518c528Fd8cf22D2f8222DDdca3"
        Type = ""
    [[Games.Contracts]]
        Address="0xB6C9494621cf6fB1dA3f78EAf1B53e756EE40bc4"
        Type = ""
    [[Games.Contracts]]
        Address="0x3364a8E0cE0C05cf333531fAe764f06B98902718"
        Type = ""
    [[Games.Contracts]]
        Address="0x1a802826F12D5b0128AA2E21689fcA84E8F57132"
        Type = ""
    [[Games.Contracts]]
        Address="0xe372ED8d188517eF4d4bC464C0c068d2002E2903"
        Type = ""
    [[Games.Contracts]]
        Address="0xB11822C35a5Ffda4b569E93173CB1fA865D6A666"
        Type = ""
    [[Games.Contracts]]
        Address="0xc3AB64924E552646a0Fa119DC4Ff1B2cD8Ab2D84"
        Type = ""
    [[Games.Contracts]]
        Address="0x2e95319eb7c9051225f1c23f4c8f211b3be91b68"
        Type = ""
    [[Games.Contracts]]
        Address="0x6Ee6b3524353739191Ec12d573bD6c429A23632d"
        Type = ""
    [[Games.Contracts]]
        Address="0xce7467531f0Fa949e6cd09A3B8F39e287eec33b8"
        Type = ""
    [[Games.Contracts]]
        Address="0xeAe6fD7d8c1740f3F1B03e9a5C35793cD260B9A6"
        Type = ""
    [[Games.Contracts]]
        Address="0x55b7B8F50E1d45D34981C2F251606e484a3f97Fe"
        Type = ""
    [[Games.Contracts]]
        Address="0xaf93fE4b2dA55A723a1bf91Ab67F9a09ea1bceD2"
        Type = ""
    [[Games.Contracts]]
        Address="0xb9bECa40F6E28d27b1B49FD98ad5b2a3bc1D9A6B"
        Type = ""
    [[Games.Contracts]]
        Address="0xd66E157AA2f4e34C66C4f915c72b8C3dC9E15d39"
        Type = ""
    [[Games.Contracts]]
        Address="0x829c1A958CD0177FB87cA5e01d00F85310DC51d6"
        Type = ""
    [[Games.Contracts]]
        Address="0x2a1276a103ad0727baedee444e37ce9ee07a3efe"
        Type = ""
    [[Games.Contracts]]
        Address="0x57cf1E34075e7304bf9380817E796B3cC80b1BeD"
        Type = ""
    [[Games.Contracts]]
        Address="0xEAa95488ADD154A4e3686638e5b38D61F6Ca728e"
        Type = ""
    [[Games.Contracts]]
        Address="0xA0e1e9AD67b5B6C053489d9882d7b8eD4546D8cb"
        Type = ""

[[Games]]
    Name = "Decentraland"
    ID  = "decentraland"
    [[Games.Contracts]]
        Address="0xb3bca6f5052c7e24726b44da7403b56a8a1b98f8"
        Type = ""
    [[Games.Contracts]]
        Address="0x46fbcfd32ea671caa21897c09072cb6cb44c0bc9"
        Type = ""
    [[Games.Contracts]]
        Address="0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d"
        Type = ""
    [[Games.Contracts]]
        Address="0xcca95e580bbbd04851ebfb85f77fd46c9b91f11c"
        Type = ""
    [[Games.Contracts]]
        Address="0x79c1fdaba012b9a094c495a86ce5c6199cf86368"
        Type = ""
    [[Games.Contracts]]
        Address="0x151b11892dd6ab1f91055dcd01d23d03a2c47570"
        Type = ""
    [[Games.Contracts]]
        Address="0x59ccfc50bd19dcd4f40a25459f2075084eebc11e"
        Type = ""
    [[Games.Contracts]]
        Address="0xea06746f1bd82412f9f243f6bee0b8194d67a67d"
        Type = ""
    [[Games.Contracts]]
        Address="0xbee217bfe06c6faaa2d5f2e06ebb84c5fb70d9bf"
        Type = ""
    [[Games.Contracts]]
        Address="0xf886313f213c198458eba7ae9329525e64eb763a"
        Type = ""
    [[Games.Contracts]]
        Address="0x0a820c4e3a9c8d89c9a3e78dfe993b3885b229fa"
        Type = ""
    [[Games.Contracts]]
        Address="0x959e104e1a4db6317fa58f8295f586e1a978c297"
        Type = ""
    [[Games.Contracts]]
        Address="0x8e5660b4ab70168b5a6feea0e0315cb49c8cd539"
        Type = ""

[[Games]]
    Name = "EvolutionLand"
    ID  = "evolution_land"
    [[Games.Contracts]]
        Address="0x9469d013805bffb7d3debe5e7839237e535ec483"
        Type = ""
    [[Games.Contracts]]
        Address="0x9f284e1337a815fe77d2ff4ae46544645b20c5ff"
        Type = ""
    [[Games.Contracts]]
        Address="0xf45e406067798d2df7913704edcc2ac8d07f3d9e"
        Type = ""
    [[Games.Contracts]]
        Address="0xe19866986976e84b2c2691169c9f9b1baa433893"
        Type = ""
    [[Games.Contracts]]
        Address="0x6b0940772516b69088904564a56d09cfe6bb3d85"
        Type = ""
    [[Games.Contracts]]
        Address="0x358dba28848cca268ba8a76b65e5b3ef9ef92238"
        Type = ""
    [[Games.Contracts]]
        Address="0xd4b784ae5c12153d11ca55853d832d2a2d514a08"
        Type = ""
    [[Games.Contracts]]
        Address="0x19e22a73a046f19ecb51a46ace4ca7a4bb7c20c6"
        Type = ""
    [[Games.Contracts]]
        Address="0x8469a695d70033ecd170c82be1253842162aa77e"
        Type = ""
    [[Games.Contracts]]
        Address="0x1320994fa466e19f17b143995999c7275eae50e1"
        Type = ""
    [[Games.Contracts]]
        Address="0x4dd50324697885ce32b4a7e4e563ef2483dd0e83"
        Type = ""
    [[Games.Contracts]]
        Address="0x5520ec6a7e33ea5d4b6bef89ce6e637d62d301a6"
        Type = ""
    [[Games.Contracts]]
        Address="0xd16f8a3c363fe05b5085937b5ba8a9e91d01a951"
        Type = ""
    [[Games.Contracts]]
        Address="0x14a4123da9ad21b2215dc0ab6984ec1e89842c6d"
        Type = ""
    [[Games.Contracts]]
        Address="0x1349d7f2cf992c2533b78e92220b61cc988260cf"
        Type = ""
    [[Games.Contracts]]
        Address="0xd25ba3ee5f67b6b61620406646e709720015550b"
        Type = ""
    [[Games.Contracts]]
        Address="0xbdd20d63ff83f5ce8359ee9c7842b4a621f601c2"
        Type = ""
    [[Games.Contracts]]
        Address="0xa99289f6742c3f4da809c51dfc6600b12849b20b"
        Type = ""
    [[Games.Contracts]]
        Address="0xf414144bff74872ef81027fc9df7ab51c15d3b98"
        Type = ""
    [[Games.Contracts]]
        Address="0x569bcb21cf3d83121f95ad61f47d14da192d4cb7"
        Type = ""
    [[Games.Contracts]]
        Address="0x7c87565b305726c4d2f6483dfd68a7fad0eb5170"
        Type = ""
    [[Games.Contracts]]
        Address="0x1fc9697e9992a54d6e9b443c4fc1bb4994f29d03"
        Type = ""
    [[Games.Contracts]]
        Address="0xefaa3ae3d01886a0268eb74f0d63aa031c39dc3b"
        Type = ""
    [[Games.Contracts]]
        Address="0x65558b5b48dca1ed00dbd677c02faba8a6eb270f"
        Type = ""
    [[Games.Contracts]]
        Address="0xf0e5af5380edf5295279dd0d5b930d3b9408867d"
        Type = ""
    [[Games.Contracts]]
        Address="0x64edf5f3fc522c7e7b46b553f4b8b98149888b5b"
        Type = ""
    [[Games.Contracts]]
        Address="0x74744f8f676feba599e6668a8513b97bf5306e77"
        Type = ""
    [[Games.Contracts]]
        Address="0x36f061bc3314793c5637fb79421294c061ead108"
        Type = ""
    [[Games.Contracts]]
        Address="0xe0cb8d4de94a13c707e6c5d8370fafec653d1b67"
        Type = ""
    [[Games.Contracts]]
        Address="0xf4f5da5d5141f73998bb9c2ef548bf47104e9d8f"
        Type = ""
    [[Games.Contracts]]
        Address="0xc65a6cb78994dc4c4e8397e5836150591224e588"
        Type = ""
    [[Games.Contracts]]
        Address="0xf5e775bbdca4388269676ebe4166b1462352a02b"
        Type = ""
    [[Games.Contracts]]
        Address="0x145d71f0ed719f350dd571baa04e525fdf91ca95"
        Type = ""
    [[Games.Contracts]]
        Address="0xa4db07460c7473ef3aaf2c26da46b00a4d986d72"
        Type = ""
    [[Games.Contracts]]
        Address="0xd38c8a78f4a554bcba3bd829310e451a23f2e5ee"
        Type = ""
    [[Games.Contracts]]
        Address="0x335e07b1465d1158b8300c675ee8903c65981266"
        Type = ""
    [[Games.Contracts]]
        Address="0x0698392380d9ee265ee413c813b5e30b905c887e"
        Type = ""
    [[Games.Contracts]]
        Address="0x649fdf6ee483a96e020b889571e93700fbd82d88"
        Type = ""
    [[Games.Contracts]]
        Address="0x171594fa19aa9b8caa3b02f04558f6c6198ac9fd"
        Type = ""
    [[Games.Contracts]]
        Address="0x8bf8df34297276fab4d6f4e785fd8b91773493e0"
        Type = ""
    [[Games.Contracts]]
        Address="0x2f3ae1484f812df67b7feb2a7d53b2ee43aaddcd"
        Type = ""
    [[Games.Contracts]]
        Address="0x6171ca93339486d57859b80f56a725f44ab6a9cf"
        Type = ""
    [[Games.Contracts]]
        Address="0xba78d7b00eb3da78b34fa9b57a86c7fb8c7e77fc"
        Type = ""
    [[Games.Contracts]]
        Address="0x0e173cca6591f00bcb81345d21bc7a218be6256b"
        Type = ""
    [[Games.Contracts]]
        Address="0x4be9b1237f2c8aa1709123924e3c2eda97e30a4e"
        Type = ""
    [[Games.Contracts]]
        Address="0x4ab8567d92eb454c3f9548a0851e10ea7550659d"
        Type = ""
    [[Games.Contracts]]
        Address="0x77c17ea6d547f6e8506730e2ce8b5b047b10a326"
        Type = ""
    [[Games.Contracts]]
        Address="0xf023a9f328f34741110433c7d4c38bc3972c4e53"
        Type = ""
    [[Games.Contracts]]
        Address="0xcf50e8acbbe8215cc99139994683e3d2dbdab6cd"
        Type = ""
    [[Games.Contracts]]
        Address="0x4710573b853fdd3561cb4f60ec9394f0155d5105"
        Type = ""
    [[Games.Contracts]]
        Address="0x3d5b127eb5295ee3ae376d5c5870ade3226ca993"
        Type = ""
    [[Games.Contracts]]
        Address="0xf046b87750d0060c5c4d9c1eff824ee4fb051f92"
        Type = ""
    [[Games.Contracts]]
        Address="0xb5e00e37ded86ec82992dd1c842d5e23aeee2329"
        Type = ""
    [[Games.Contracts]]
        Address="0x1b21fdda5cfc02279667b9ff4408312ce7f01966"
        Type = ""
    [[Games.Contracts]]
        Address="0xa2e729a64b32ca79f46de3d8cc03fa9724d623f7"
        Type = ""
    [[Games.Contracts]]
        Address="0xab5e712d3f90d68b2356b613a7af6012bbd301ca"
        Type = ""
    [[Games.Contracts]]
        Address="0xa70abeaca1d6bba0f511758a0d66b7f59fd3f166"
        Type = ""
    [[Games.Contracts]]
        Address="0xfc5824ffe69524b585740b65969bc87f982a4b87"
        Type = ""
    [[Games.Contracts]]
        Address="0x7469966be391e8fe5e85ab972819560c7c3d6e4c"
        Type = ""
    [[Games.Contracts]]
        Address="0x0336a843603f94451b2a61d3b6b8dc5dc64b79f3"
        Type = ""
    [[Games.Contracts]]
        Address="0xa35903b414c851fc48b593f4777394a6a63067e6"
        Type = ""
    [[Games.Contracts]]
        Address="0xa665271c365f9d9a149866574a5b047dd9e3d31b"
        Type = ""
    [[Games.Contracts]]
        Address="0x550366ade903e488ffe70074526f9dae901cd397"
        Type = ""
    [[Games.Contracts]]
        Address="0xbbdd374a1d106b5cc53a4b3954ae99b9502b4db6"
        Type = ""
    [[Games.Contracts]]
        Address="0xf44c58e703070d4ce7b2440533f29f62713ee071"
        Type = ""
    [[Games.Contracts]]
        Address="0xae5b5aa6063a2208063f903e6c566b5781a3d9c4"
        Type = ""
    [[Games.Contracts]]
        Address="0xeee4a506c662aa1b5581149fdc4e53862359d292"
        Type = ""
    [[Games.Contracts]]
        Address="0xa9203f3303126243c8d181006ab03b2474e3c084"
        Type = ""
    [[Games.Contracts]]
        Address="0xe0a0489d93aeb831a04e8b631ebd9827a4db4a58"
        Type = ""
    [[Games.Contracts]]
        Address="0x4394271f0fa7b20b4a2378269b1ef99ddd4ed543"
        Type = ""
    [[Games.Contracts]]
        Address="0xdc7cbfa9a172e0418107799ff25b2989a21743eb"
        Type = ""
    [[Games.Contracts]]
        Address="0x09f8b2a267bd3b8ef53b085c4a3b683257713f37"
        Type = ""
    [[Games.Contracts]]
        Address="0xfe51ee435667ab8730cdc11d05b0cac237a4d521"
        Type = ""
    [[Games.Contracts]]
        Address="0x2995bbb4a6116e4df8a171443bfbb682065295d0"
        Type = ""
    [[Games.Contracts]]
        Address="0xbe0b85ab71af79d0190ef53a70334a83be51874d"
        Type = ""
    [[Games.Contracts]]
        Address="0x2f67ee58945a3d13801e6f016aa84abdce6d72a7"
        Type = ""
    [[Games.Contracts]]
        Address="0x7f23e4a473db3d11d11b43d90b34f8a778753e34"
        Type = ""
    [[Games.Contracts]]
        Address="0x31a37120d1e4ee1cdad773d22dab67e968ba3c7b"
        Type = ""
    [[Games.Contracts]]
        Address="0xb0c85c099094e73ffc1df23c8309a8b14c64420a"
        Type = ""
    [[Games.Contracts]]
        Address="0xc28d31eacec212e2f0606f718bfe936a29b98d1c"
        Type = ""
    [[Games.Contracts]]
        Address="0xab1Cb6a9467b77B9451c1c61140FB34494baFFDD"
        Type = ""
    [[Games.Contracts]]
        Address="0x8d7af9d2310016712b8f269df266f957cb12a27b"
        Type = ""

[[Games]]
    Name = "Guild of Guardians"
    ID  = "guild_of_guardians"
    [[Games.Contracts]]
        Address="0xc253cbc67556e797fdb750a031d5e6208c423ad5"
        Type = ""
