LogFile = "polygon_gfdp.log"
LogPath = "./"
LogLevel = "Info"
PrivKey = ""
DBURI = "mongodb+srv://cz:Solong2020@cluster1.g9w77.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
#DBURI = "mongodb+srv://gametaverse:gametaverse2021@cluster0.fnwxw.mongodb.net/d_gametaverse?retryWrites=true&w=majority"
Chain = "polygon"
ChainID = 137
#RPCAddr = "https://rpc-mainnet.maticvigil.com"
#RPCAddr = "https://polygon-rpc.com/"
RPCAddr = "https://rpc.ankr.com/polygon/89a1577615a713dddcd59aed5762cb3851fe3d050eb6c7e2a26fe39c38cb97d9"
BottomBlock = 9000000
ForwardInterval = 1.5
BackwardInterval = 1.0
ForwardWorks = 1
BackwardWorks = 20
