LogFile = "avax_gamefidata.log"
LogPath = "./"
LogLevel = "Info"
Chain = "avax"
ChainID = 43114
RPCAddr = "https://rpc.ankr.com/avalanche/89a1577615a713dddcd59aed5762cb3851fe3d050eb6c7e2a26fe39c38cb97d9"
BottomBlock = 20000
ForwardInterval = 1.0
BackwardInterval = 1.0
ForwardWorks = 1
BackwardWorks = 20