RPCAddr = "127.0.0.1:8088"
LogFile = "sti.log"
LogPath = "./"
LogLevel = "Info"
DBURI = "mongodb+srv://cz:Solong2020@cluster1.g9w77.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
#DBURI = "mongodb+srv://gametaverse:gametaverse2021@cluster0.fnwxw.mongodb.net/d_gametaverse?retryWrites=true&w=majority"
Vs = [
    "AxieInfinity",
    "bladescrypto",
    "YieldGuild",
    "revv_token",
    "zed_run",
    "AlienWorlds",
    "splinterlands",
    "BlackpoolHQ",
    "illuviumio",
    "MOBOX_Official",
    "TowerToken",
    "sorarehq",
    "highstreetworld",
    "Nifty_Island",
    "staratlas",
    "GuildOfGuardian",
    "MUSTCometh",
    "TheSandboxGame",
    "OVRtheReality",
    "fearnfts",
    "ParallelNFT",
    "AaveAave",
    "defi_land",
    "starterra_io",
    "auroryproject",
    "CryptoZoonBSC",
    "NineChronicles",
    "FarmersWorldNFT",
    "cradlesio",
    "wanaka_farm",
    "knightwarp2e",
    "nyanheroes",
    "CryptobayVip",
    "binary_x",
    "StepHeroNFTs",
    "PolkaCity",
    "binamonok",
    "raritygame",
    "kakanftworld",
    "townstargame",
    "RadioCacaNFT",
    "RPLANETio",
    "MyDeFiPet",
    "binapet",
    "epicheroio",
    "kolobok_io",
    "petkingdom_game",
    "dragonwarriorio",
    "farming_tales",
    "NovaRallyWAX",
    "overlordbsc",
    "mycryptoheroes_",
    "coin_pirates",
    "xwg_games",
    "faraland_io",
    "herocatgamefi",
    "bfh_global",
    "CoPuppy_BSC",
    "neondistrictrpg",
    "knightlandsgame",
    "CrusaderBSC",
    "cryptoplanet_fi",
    "playsnook_com",
    "solifenft",
    "ProjectSeedGame",
    "openerahq",
    "ninjaprotocol",
    "zoogamepro",
    "HeroFiio",
    "risingsuntoken",
    "NftMamo",
    "mymasterwar",
    "defivillegame",
    "cryptominesapp",
    "forestknight_io",
    "risingsuntoken?",
    "spiritclashccg",
    "thetanarena",
    "starmongame",
    "galaxynftgame",
    "polker_PKR",
    "runemmo",
    "mycryptosaga_",
    "clash_dome",
    "AlchemyToys",
    "monsterbudsnft",
    "herobattlebsc",
    "DarkCountryGame",
    "MistNft",
    "blockfarmclub",
    "prelax_io",
    "cryptospells_en",
    "verofarmgames",
    "Evolution_Land",
    "funnycatsnft",
    "f1deltatime",
    "CompanionsNFT",
    "cryptosoccerof",
    "planetsandbox",
    "LeagueKingdoms",
    "influenceth",
    "thetanarena",
    "metafish_bsc",
    "decentraland",
    "osirismetaverse",
    "arconametaverse",
    "nftspaceheroes",
    "Immersys",
    "PolkaMonsterBSC",
    "ancientrealmsio",
    "galaxynftgame",
    "KuraiMetaverse",
    "StarLinkETH",
    "yoheroyolo",
    "NetVRk1",
    "PlayEmberSword",
    "beyondearth_nft",
    "osirismetaverse",
    "nemesisgg",
    "warenaofficial",
    "KabyArena",
    "theufotoken",
    "MetaWarsNFT",
    "genopets",
    "StarSharks_SSS",
    "aavegotchi",
    "0xmeligames",
    "MetaverseMiner",
    "SIPHERxyz",
    "LeagueKingdoms",
    "the_phantom_g",
    "bnbheroes",
    "placewar_game",
    "talecraftio",
    "IrreverentLabs"
]
TwitterInterval = 600
TwitterCount = 100
TelegramToken = "1790999840:AAFf92ROKe7x8gy46eoY5CAKNiUnLSf25zk"
Groups = [
    -1001387862696
]
KeyWords = [
    "airdrop",
    "ama",
    "ido",
    "igo",
    "raindrop",
    "farming",
    "live stream",
    "contest",
    "development progress"
]
TokenRPC = "http://127.0.0.1:8090/twitterspy/api/v1/token"
