RPCAddr = "127.0.0.1:8088"
LogFile = "sti.log"
LogPath = "./"
LogLevel = "Info"
Vs = [
    "fomosaurus",
    "dcfgod",
    "CryptoBart95",
    "Cryptoyieldinfo",
    "Tetranode",
    "CryptoMaestro",
    "Chase_NL",
    "Crypto_Gambit_",
    "C0inAlchemist",
    "icebergy_",
    "gMAKcrypto",
    "bitcoin_whales",
    "shroom_daddy",
    "FesCrypto",
    "TheShual",
    "ChartSimpson",
    "gMAKcrypto",
    "0xRafi",
    "fomosaurus",
    "CryptoMessiah",
    "0x_Osprey",
    "SBF_Alameda"
]
TwitterInterval = 600
TwitterCount = 100
TelegramToken = "1790999840:AAFf92ROKe7x8gy46eoY5CAKNiUnLSf25zk"
Groups = [
    -1001387862696
]
NoCoins = [
    "ETH",
    "BTC",
]
MongoUser = "cz"
MongoPasswd = "Solong2020"
MongoDBName = "db_cti"
